/* 🏠 我们的小屋：一间只属于你们俩的小房间。一起做过的事会变成屋里的小物件——合照变成墙上的相框、散步捡回一片叶子、做到的约定变成一张奖状、捡到的漂流瓶摆在窗台……TA 也会时不时添一件东西，每件都有一段故事。东西能拖来拖去摆 */
if (window.__gyxHome) return; window.__gyxHome = 1;
X.feat('gyxHome', { n: '🏠 我们的小屋', desc: '一起做过的事变成屋里的小物件，每件都有故事，能自己摆' });
const S = X.store('home');
let D = { rooms: {}, cfg: { wall: 0 } };   // rooms[cid] = {items:[{id, ico, name, story, x, y, at, src, by}]}
const WALLS = [['#f6efe6', '#d9c3a5', '暖木'], ['#eef3f8', '#b9c7d6', '清晨'], ['#fbeef2', '#e3b7c4', '粉色'], ['#2c2f45', '#5a4a3d', '夜晚']];
const roomOf = cid => (D.rooms[String(cid)] = D.rooms[String(cid)] || { items: [] });
function put(cid, o) { const R = roomOf(cid); if (o.src && (R.items.some(x => x.src === o.src) || (D.gone || []).includes(o.src))) return null; const it = Object.assign({ id: 'hm' + Date.now().toString(36) + Math.random().toString(36).slice(2, 4), x: X.rnd(.08, .86), y: o.ico && /🖼️|🏅|🗓️|🌌/.test(o.ico) ? X.rnd(.08, .4) : X.rnd(.55, .85), at: Date.now(), by: 'auto' }, o); R.items.push(it); return it; }
function collect() {
    let n = 0; X.chars().forEach(c => { const cid = String(c.id);
        try { (window.gyxDuoData ? window.gyxDuoData().pics : []).filter(x => x.cid === cid).forEach(x => { if (put(cid, { ico: '🖼️', name: '合照相框', story: `${new Date(x.at).toLocaleDateString()} 拍的。TA 说：「${x.say}」`, src: 'duo:' + x.id, img: x.src })) n++; }); } catch (e) {}
        try { (window.gyxWalkData ? window.gyxWalkData().walks : []).filter(x => x.cid === cid).forEach(x => { if (put(cid, { ico: X.pick(['🍂', '🌿', '🪨', '🌼']), name: '散步捡回来的', story: `${new Date(x.start).toLocaleDateString()} 一起走了 ${Math.round(x.dist)} 米。${x.diary || ''}`, src: 'walk:' + x.id })) n++; }); } catch (e) {}
        try { (window.gyxPromiseData ? window.gyxPromiseData().list : []).filter(x => x.cid === cid && x.done === true).forEach(x => { if (put(cid, { ico: '🏅', name: '奖状', story: `约好的「${x.what}」，做到了。${x.reward ? '奖励：' + x.reward : ''}`, src: 'pr:' + x.id })) n++; }); } catch (e) {}
        try { (window.gyxBottleData ? window.gyxBottleData().got : []).filter(x => x.kept && x.from === cid).forEach(x => { if (put(cid, { ico: '🍾', name: '窗台上的漂流瓶', story: x.text, src: 'bt:' + x.id })) n++; }); } catch (e) {}
    }); return n;
}
async function gift(c) {
    const R = roomOf(c.id), have = R.items.map(x => x.name).join('、');
    let j = X.bailu() ? null : X.json(await X.ask(`${X.who(c)}\n你们有一间小屋，现在屋里有：${have || '（空的）'}。\n你想给小屋添一件小东西，和你们最近的事有关。\n最近的聊天：\n${X.recent(c, 16)}\n只输出 JSON：{"ico":"一个 emoji","name":"东西的名字（8 字内）","story":"为什么放这个（你的口吻，40~80 字）"}`));
    if (!j || !j.name) { const P = [['🪴', '一盆小绿萝', '它很好养，跟我一样，你给一点点关心就能长很久。'], ['🕯️', '一根香薰蜡烛', '下雨天点上，屋里就有你喜欢的味道了。'], ['🧸', '小熊', '我不在的时候让它陪你。不许抱它比抱我还紧。'], ['☕', '两个马克杯', '一个你的一个我的，杯底写了名字。'], ['📻', '旧收音机', '晚上开着，像有人在说话，你就不会怕了。'], ['🧣', '一条围巾', '挂在门口，出门记得戴。'], ['🎐', '风铃', '风一吹它就响，像我在叫你。']]; const p = X.pick(P.filter(x => !R.items.some(i => i.name === x[1])).concat([P[0]])); j = { ico: p[0], name: p[1], story: (X.cards(['情话'], c, 1)[0] || p[2]) }; }
    const it = put(c.id, { ico: String(j.ico || '🎁').slice(0, 4), name: String(j.name).slice(0, 12), story: X.plain(j.story), by: 'ta' }); await S.set('d', D); return it;
}
let DRAG = null;
window.gyxHomeDown = (e, cid, id) => { e.preventDefault(); e.stopPropagation(); DRAG = { cid, id, moved: false }; const mv = ev => { const room = document.getElementById('gyxHomeRm'), r = room.getBoundingClientRect(), p = ev.touches ? ev.touches[0] : ev, it = roomOf(cid).items.find(x => x.id === id); if (!it) return; DRAG.moved = true; it.x = Math.max(0, Math.min(.94, (p.clientX - r.left) / r.width - .03)); it.y = Math.max(0, Math.min(.9, (p.clientY - r.top) / r.height - .05)); const el = document.getElementById('hmi_' + id); if (el) { el.style.left = it.x * 100 + '%'; el.style.top = it.y * 100 + '%'; } }, up = () => { removeEventListener('mousemove', mv); removeEventListener('touchmove', mv); removeEventListener('mouseup', up); removeEventListener('touchend', up); if (DRAG && !DRAG.moved) window.gyxHomeSee(cid, id); DRAG = null; S.set('d', D); }; addEventListener('mousemove', mv); addEventListener('touchmove', mv, { passive: false }); addEventListener('mouseup', up); addEventListener('touchend', up); };
window.gyxHomeSee = (cid, id) => { const it = roomOf(cid).items.find(x => x.id === id), b = document.getElementById('gyxHomeInfo'); if (!it || !b) return; b.innerHTML = `<div style="display:flex;gap:10px;align-items:center"><span style="font-size:34px">${it.img ? `<img src="${it.img}" style="width:46px;height:46px;object-fit:cover;border-radius:6px">` : X.esc(it.ico)}</span><div style="flex:1"><b contenteditable="true" onblur="gyxHomeEdit('${cid}','${id}','name',this.innerText.trim())">${X.esc(it.name)}</b><div class="gyx-tip">${new Date(it.at).toLocaleDateString()} · ${it.by === 'ta' ? 'TA 放的' : it.by === 'me' ? '你放的' : '一起做过的事'}</div></div><span class="gyx-chip" onclick="gyxHomeEdit('${cid}','${id}','__del')">收起来</span></div><div contenteditable="true" style="margin-top:6px;outline:none;line-height:1.7" onblur="gyxHomeEdit('${cid}','${id}','story',this.innerText.trim())">${X.esc(it.story || '')}</div>`; };
window.gyxHomeEdit = async (cid, id, k, v) => { const R = roomOf(cid), it = R.items.find(x => x.id === id); if (!it) return; if (k === '__del') { R.items.splice(R.items.indexOf(it), 1); if (it.src) (D.gone = D.gone || []).push(it.src); await S.set('d', D); window.gyxHomeOpen(cid); return; } it[k] = v; await S.set('d', D); };
window.gyxHomeAdd = async cid => { const ico = (document.getElementById('gyxHmIco') || {}).value || '🎁', nm = ((document.getElementById('gyxHmNm') || {}).value || '').trim(); if (!nm) return; const it = put(cid, { ico: ico.trim().slice(0, 4), name: nm, story: ((document.getElementById('gyxHmSt') || {}).value || '').trim(), by: 'me' }); await S.set('d', D); window.gyxHomeOpen(cid); if (it) setTimeout(() => window.gyxHomeSee(cid, it.id), 50); };
window.gyxHomeGift = async cid => { const c = X.char(cid); if (!c) return; const it = await gift(c); window.gyxHomeOpen(cid); if (it) setTimeout(() => window.gyxHomeSee(cid, it.id), 50); };
window.gyxHomeWall = v => { D.cfg.wall = v; S.set('d', D); window.gyxHomeOpen(); };
window.gyxHomeOpen = function (who) {
    const c = X.char(who) || X.cur(); if (!c) return; const cid = String(c.id); if (collect()) S.set('d', D); const R = roomOf(cid), w = WALLS[D.cfg.wall] || WALLS[0];
    X.panel('gyxHomeOv', '🏠 我们的小屋', `<div class="gyx-row">${X.whoSel(cid, 'gyxHomeOpen')}${WALLS.map((x, i) => `<span class="gyx-chip${i === D.cfg.wall ? ' on' : ''}" onclick="gyxHomeWall(${i})">${x[2]}</span>`).join('')}</div>
        <div id="gyxHomeRm" class="hm-rm" style="--wa:${w[0]};--fl:${w[1]}"><div class="hm-win">🪟</div>${R.items.map(x => `<div id="hmi_${x.id}" class="hm-it" style="left:${x.x * 100}%;top:${x.y * 100}%" onmousedown="gyxHomeDown(event,'${cid}','${x.id}')" ontouchstart="gyxHomeDown(event,'${cid}','${x.id}')" title="${X.esc(x.name)}">${x.img ? `<img src="${x.img}">` : X.esc(x.ico)}</div>`).join('')}${R.items.length ? '' : `<div class="hm-empty">${X.v('屋里还空空的。', '一起做点什么，这里就会慢慢满起来。')}</div>`}</div>
        <div id="gyxHomeInfo" class="gyx-card">${R.items.length ? X.v('点一件东西看它的故事，拖着能挪位置。', '每件东西都有一段故事。') : '拍合照、散步、做到约定、捡漂流瓶……都会在这里留下东西。'}</div>
        <div class="gyx-row"><button class="gyx-btn lite" onclick="this.disabled=true;gyxHomeGift('${cid}')">让 TA 添一件</button></div>
        <div class="gyx-row"><input id="gyxHmIco" class="gyx-who" style="width:54px" value="🎁"><input id="gyxHmNm" class="gyx-who" style="flex:1" placeholder="东西"><input id="gyxHmSt" class="gyx-who" style="flex:2" placeholder="它的故事"><button class="gyx-btn" onclick="gyxHomeAdd('${cid}')">放进去</button></div>`);
};
async function tick() { if (!X.on('gyxHome')) return; if (collect()) await S.set('d', D); }
X.ctx(id => { const R = D.rooms[String(id)]; if (!R || !R.items.length) return ''; return `【你们的小屋里有】${R.items.slice(-8).map(x => x.name).join('、')}。`; }, 'gyxHome');
X.action({ key: 'gyx_home', label: '给你们的小屋添一件东西', hint: '我们的小屋', need: c => !roomOf(c.id).items.some(x => x.by === 'ta' && Date.now() - x.at < 5 * 864e5),
    run: async c => { const it = await gift(c); if (!it) return null; return (await X.reach(c, `你刚给你们的小屋添了「${it.name}」。告诉她，说说为什么放它`)) ? '给小屋添了' + it.name : null; } }, 'gyxHome');
X.today(() => { const rows = []; X.chars().forEach(c => roomOf(c.id).items.filter(x => X.day(new Date(x.at)) === X.day()).forEach(x => rows.push({ t: x.ico, x: X.esc(x.name) + (x.by === 'ta' ? '（TA 放的）' : ''), go: `gyxHomeOpen('${c.id}')` }))); return { title: '🏠 小屋里多了', rows }; }, 'gyxHome');
X.widget('gyxHomeW', { n: '我们的小屋', sizes: ['s', 'm'], tap: () => window.gyxHomeOpen(), r: w => { const c = X.cur(), L = c ? roomOf(c.id).items : []; return X.gw(w, '🏠', '我们的小屋', L.length ? [L.slice(-6).map(x => x.img ? '🖼️' : X.esc(x.ico)).join(''), L.length + ' 件东西'] : ['还空着']); } }, 'gyxHome');
X.mem({ k: 'gyxHome', ico: '🏠', n: '我们的小屋', d: '屋里每件东西和它的故事', items: c => roomOf(c.id).items, text: x => x.name + '：' + (x.story || ''), edit: (x, v) => { const i = v.indexOf('：'); if (i > 0) { x.name = v.slice(0, i); x.story = v.slice(i + 1); } else x.story = v; }, del: (c, i) => { const it = roomOf(c.id).items.splice(i, 1)[0]; if (it && it.src) (D.gone = D.gone || []).push(it.src); }, meta: x => x.ico + ' · ' + new Date(x.at).toLocaleDateString(), save: () => S.set('d', D) }, 'gyxHome');
X.css('gyxHomeCss', `.hm-rm{position:relative;height:52vh;border-radius:18px;overflow:hidden;background:linear-gradient(var(--wa) 0 62%,var(--fl) 62%);box-shadow:inset 0 -2px 0 rgba(0,0,0,.05);touch-action:none}.hm-win{position:absolute;left:40%;top:10%;font-size:56px;opacity:.7}.hm-it{position:absolute;font-size:34px;cursor:grab;user-select:none;filter:drop-shadow(0 3px 3px rgba(0,0,0,.18));transition:transform .15s}.hm-it:hover{transform:scale(1.15)}.hm-it img{width:44px;height:44px;object-fit:cover;border:4px solid #fff;border-radius:3px;box-shadow:0 2px 6px rgba(0,0,0,.25)}.hm-empty{position:absolute;left:0;right:0;top:44%;text-align:center;color:#a99;font-size:14px}`);
X.mini({ id: 'gyxHome', icon: '🏠', title: '我们的小屋', desc: '一起做过的事变成屋里的小物件', cat: '回忆', onOpen: () => window.gyxHomeOpen() });
(async () => { D = Object.assign(D, await S.get('d', {})); D.rooms = D.rooms || {}; D.cfg = Object.assign({ wall: 0 }, D.cfg || {}); setTimeout(tick, 30000); setInterval(tick, 120000); })();
