/* 🧾 恋爱审批（OA 版）：想熬夜、想喝奶茶、想买那件衣服、想请假晚点回消息？先打报告！填表、选紧急程度、提交给 TA 审批——TA 会通过、驳回或者「附条件通过」，盖章、写批注。TA 也会给你打报告（申请抱抱、申请见面、申请多打一局游戏），你来批 */
if (window.__gyxOA) return; window.__gyxOA = 1;
X.feat('gyxOA', { n: '🧾 恋爱审批', desc: 'OA 式打报告：你提申请 TA 审批、TA 提申请你审批，盖章写批注' });
const S = X.store('oa');
let D = { list: [], seq: 0, cfg: { max: 10 } };   // [{id, no, cid, by:'me'|'ta', type, why, amt, urg, at, due, res:null|'通过'|'驳回'|'附条件通过', note, cond, rat}]
const TYPES = [['熬夜申请', '🌙', '时长'], ['奶茶 / 零食申请', '🧋', '数量'], ['购物申请', '🛍️', '金额'], ['请假申请（晚点回消息）', '🏖️', '时长'], ['撒娇申请', '🥺', ''], ['抱抱申请', '🤗', '时长'], ['见面申请', '📍', ''], ['游戏时长申请', '🎮', '时长'], ['免罚申请', '🙏', ''], ['其它申请', '📄', '']];
const URG = ['普通', '加急', '特急'];
const icoOf = t => (TYPES.find(x => x[0] === t) || [, '📄'])[1];
const no = () => { D.seq = (D.seq || 0) + 1; const d = new Date(); return `LOVE-${d.getFullYear()}${String(d.getMonth() + 1).padStart(2, '0')}${String(d.getDate()).padStart(2, '0')}-${String(D.seq).padStart(3, '0')}`; };
const stamp = (res, nm) => { const ok = res !== '驳回', col = ok ? '#e0403a' : '#7a7a7a'; return `<svg class="oa-stamp" viewBox="0 0 100 100" width="84" height="84"><circle cx="50" cy="50" r="44" fill="none" stroke="${col}" stroke-width="4"/><circle cx="50" cy="50" r="36" fill="none" stroke="${col}" stroke-width="1.5"/><text x="50" y="47" text-anchor="middle" font-size="${res === '附条件通过' ? 12 : 18}" font-weight="700" fill="${col}">${res === '附条件通过' ? '有条件通过' : res === '通过' ? '同 意' : '驳 回'}</text><text x="50" y="66" text-anchor="middle" font-size="9" fill="${col}">${X.esc(String(nm).slice(0, 6))}</text></svg>`; };
async function taDecide(c, x) {
    const h = new Date().getHours();
    if (!X.bailu()) { const j = X.json(await X.ask(`${X.who(c)}\n她给你打了一份报告，请你审批（像领导批 OA，但你是她男朋友）：\n类型：${x.type}\n事由：${x.why || '（没写）'}\n${x.amt ? '数量 / 时长 / 金额：' + x.amt + '\n' : ''}紧急程度：${x.urg}\n现在 ${h} 点。\n按你的性格和对她的关心决定：通过 / 驳回 / 附条件通过（附条件要写清条件）。批注要有你的口吻，20~60 字。\n只输出 JSON：{"res":"通过 或 驳回 或 附条件通过","note":"批注","cond":"条件（没有就空）"}`)); if (j && ['通过', '驳回', '附条件通过'].includes(j.res)) return { res: j.res, note: X.plain(j.note || ''), cond: X.plain(j.cond || '') }; }
    let res = Math.random() < .6 ? '通过' : Math.random() < .5 ? '附条件通过' : '驳回';
    if (/撒娇|抱抱|见面/.test(x.type)) res = '通过'; if (/熬夜/.test(x.type) && (h >= 1 && h < 6)) res = '驳回';
    const cond = res === '附条件通过' ? X.pick(['先喝一杯水', '明天早点睡', '买完给我看看', '少糖少冰', '回来亲我一下', '十二点前必须结束']) : '';
    const note = X.pick(res === '通过' ? ['准了。下不为例（其实下次也会准）。', '同意，这种报告多打几份。', '批了，玩得开心。'] : res === '驳回' ? ['驳回。太晚了，快去睡觉。', '不批。理由：我心疼。', '驳回，附赠一个抱抱作为补偿。'] : ['可以，但是有条件。', '有条件通过，条件见下。', '原则上同意，细节再议。']);
    return { res, note, cond };
}
async function decide(x) { const c = X.char(x.cid); if (!c || x.res) return; const r = await taDecide(c, x); Object.assign(x, r, { rat: Date.now() }); await S.set('d', D); X.notify(c, `🧾 ${X.esc(X.name(c))} ${x.res === '驳回' ? X.v('驳回了你的申请', '没批你的报告') : X.v('批了你的申请', '在你的报告上盖了章')}：${X.esc(x.type)}`, x.note, () => window.gyxOAView(x.id)); if (document.getElementById('gyxOAOv')) window.gyxOAOpen(x.cid); }
async function tick() { if (!X.on('gyxOA')) return; for (const x of D.list) if (x.by === 'me' && !x.res && x.due <= Date.now()) await decide(x); }
window.gyxOATick = tick;
window.gyxOASubmit = async cid => {
    const g = id => ((document.getElementById(id) || {}).value || '').trim(); const type = g('gyxOAT') || '其它申请', why = g('gyxOAW'); if (!why) { X.toast('🧾 事由要写', '写清楚才好批'); return null; }
    const urg = g('gyxOAU') || '普通', mins = urg === '特急' ? 1 : urg === '加急' ? 3 : Math.max(1, +D.cfg.max || 10);
    const x = { id: 'oa' + Date.now().toString(36), no: no(), cid: String(cid), by: 'me', type, why, amt: g('gyxOAA'), urg, at: Date.now(), due: Date.now() + Math.round(X.rnd(.3, 1) * mins * 60000), res: null };
    D.list.unshift(x); await S.set('d', D); X.toast('🧾 ' + X.v('报告已提交', '已送审', '流程已发起'), '单号 ' + x.no); window.gyxOAView(x.id); return x;
};
window.gyxOAUrge = async id => { const x = D.list.find(y => y.id === id); if (!x) return; x.urged = (x.urged || 0) + 1; await decide(x); window.gyxOAView(id); };
window.gyxOAJudge = async (id, res) => {
    const x = D.list.find(y => y.id === id); if (!x || x.res) return; const c = X.char(x.cid); x.res = res; x.note = ((document.getElementById('gyxOANote') || {}).value || '').trim() || (res === '驳回' ? '驳回。' : '同意。'); x.cond = res === '附条件通过' ? ((document.getElementById('gyxOACond') || {}).value || '').trim() : ''; x.rat = Date.now(); await S.set('d', D);
    const r = X.bailu() ? X.pick(res === '驳回' ? ['……驳回了？那我再写一份。', '哼，打回来就打回来，我明天还交。', '呜，好吧。'] : ['批了！耶！', '谢谢领导～', '盖章了就不许反悔哦。']) : X.plain(await X.ask(`${X.who(c)}\n你给她打了「${x.type}」的报告（${x.why}），她${res}了${x.cond ? '，条件：' + x.cond : ''}，批注：「${x.note}」。说一句反应。`) || '收到。');
    X.say(c, `🧾 ${r}`); window.gyxOAView(id);
};
async function taApply(c) {
    let j = X.bailu() ? null : X.json(await X.ask(`${X.who(c)}\n你想给她打一份「恋爱报告」申请点什么（像 OA 审批，正经的格式、撒娇的内容）。\n可选类型：${TYPES.map(t => t[0]).join('、')}\n最近的聊天：\n${X.recent(c, 10)}\n只输出 JSON：{"type":"类型","why":"事由（像写报告一样，30~80 字）","amt":"数量 / 时长 / 金额（可空）","urg":"普通 或 加急 或 特急"}`));
    if (!j || !j.why) { const P = [['抱抱申请', '本人近日思念过度，工作效率下降，特申请抱抱一次，以资鼓励。', '十分钟'], ['见面申请', '经慎重考虑，申请本周末与你见面一次，地点你定，费用我出。', ''], ['游戏时长申请', '申请今晚多打一局游戏，保证打完就睡，绝不拖延。', '一局'], ['撒娇申请', '今日表现良好，特申请撒娇额度一次，望批准。', ''], ['免罚申请', '昨天回消息慢了，申请免罚一次，以后改正。', '']]; const p = X.pick(P); j = { type: p[0], why: p[1], amt: p[2], urg: X.pick(URG) }; }
    const x = { id: 'oa' + Date.now().toString(36), no: no(), cid: String(c.id), by: 'ta', type: TYPES.some(t => t[0] === j.type) ? j.type : '其它申请', why: X.plain(j.why), amt: X.plain(j.amt || ''), urg: URG.includes(j.urg) ? j.urg : '普通', at: Date.now(), res: null };
    D.list.unshift(x); await S.set('d', D); return x;
}
window.gyxOATaApply = async cid => { const c = X.char(cid) || X.cur(); const x = await taApply(c); window.gyxOAView(x.id); return x; };
window.gyxOAData = () => D;
window.gyxOAView = id => {
    const x = D.list.find(y => y.id === id); if (!x) return; const c = X.char(x.cid), me = X.me(c), ta = X.name(c), from = x.by === 'me' ? me : ta, to = x.by === 'me' ? ta : me;
    X.panel('gyxOAOv', '🧾 审批单', `<div class="oa-form"><div class="oa-hd"><b>${icoOf(x.type)} ${X.esc(x.type)}</b><span>${x.no}</span></div>
        <table><tr><th>申请人</th><td>${X.esc(from)}</td><th>审批人</th><td>${X.esc(to)}</td></tr><tr><th>提交时间</th><td colspan="3">${new Date(x.at).toLocaleString()}</td></tr><tr><th>紧急程度</th><td colspan="3"><span class="oa-urg u${URG.indexOf(x.urg)}">${x.urg}</span></td></tr>${x.amt ? `<tr><th>数量/时长/金额</th><td colspan="3">${X.esc(x.amt)}</td></tr>` : ''}<tr><th>事由</th><td colspan="3">${X.esc(x.why)}</td></tr></table>
        <div class="oa-flow"><span class="on">提交</span><i></i><span class="${x.res ? 'on' : 'cur'}">${X.esc(to)} 审批</span><i></i><span class="${x.res ? 'on' : ''}">归档</span></div>
        ${x.res ? `<div class="oa-res">${stamp(x.res, to)}<div><b>${x.res}</b>${x.cond ? `<div>条件：${X.esc(x.cond)}</div>` : ''}<div class="oa-note gyx-hand">批注：${X.esc(x.note || '')}</div><em>${new Date(x.rat).toLocaleString()}</em></div></div>`
        : x.by === 'me' ? `<div class="gyx-tip">审批中……${x.urged ? '（已催办 ' + x.urged + ' 次）' : ''}</div><button class="gyx-btn lite" onclick="this.disabled=true;this.textContent='TA 在批…';gyxOAUrge('${x.id}')">催办</button>`
        : `<textarea id="gyxOANote" class="gyx-in" rows="2" placeholder="批注（可空）"></textarea><input id="gyxOACond" class="gyx-in" style="margin-top:6px" placeholder="附加条件（选「附条件通过」时填）"><div class="gyx-row"><button class="gyx-btn" onclick="gyxOAJudge('${x.id}','通过')">同意</button><button class="gyx-btn lite" onclick="gyxOAJudge('${x.id}','附条件通过')">附条件通过</button><button class="gyx-btn lite" onclick="gyxOAJudge('${x.id}','驳回')">驳回</button></div>`}
        </div><div class="gyx-row"><button class="gyx-btn lite" onclick="gyxOAOpen('${x.cid}')">‹ 回列表</button></div>`);
};
window.gyxOAOpen = function (who, tab) {
    const c = X.char(who) || X.cur(); if (!c) return; const cid = String(c.id), L = D.list.filter(x => x.cid === cid), todo = L.filter(x => x.by === 'ta' && !x.res);
    const row = x => `<div class="oa-it" onclick="gyxOAView('${x.id}')"><span>${icoOf(x.type)}</span><div><b>${X.esc(x.type)}</b><em>${x.no} · ${x.by === 'me' ? '我提交的' : X.esc(X.name(c)) + ' 提交的'}</em></div><i class="${x.res === '驳回' ? 'no' : x.res ? 'ok' : 'wait'}">${x.res || (x.by === 'ta' ? '待我审批' : '审批中')}</i></div>`;
    X.panel('gyxOAOv', '🧾 恋爱审批', `<div class="gyx-row">${X.whoSel(cid, 'gyxOAOpen')}<button class="gyx-btn lite" onclick="this.disabled=true;gyxOATaApply('${cid}')">让 TA 打份报告</button></div>
        ${todo.length ? `<div class="oa-h">待我审批（${todo.length}）</div>${todo.map(row).join('')}` : ''}
        <details class="gyx-card" ${L.length ? '' : 'open'}><summary><b>✍️ 发起申请</b></summary><select id="gyxOAT" class="gyx-in" style="margin-top:8px">${TYPES.map(t => `<option value="${t[0]}">${t[1]} ${t[0]}</option>`).join('')}</select><textarea id="gyxOAW" class="gyx-in" rows="3" style="margin-top:6px" placeholder="事由：本人因……特申请……望批准。"></textarea><div class="gyx-row"><input id="gyxOAA" class="gyx-who" style="flex:1" placeholder="数量 / 时长 / 金额（可空）"><select id="gyxOAU" class="gyx-who">${URG.map(u => `<option>${u}</option>`).join('')}</select></div><div class="gyx-row"><button class="gyx-btn" onclick="gyxOASubmit('${cid}')">提交审批</button></div><div class="gyx-tip">普通件 TA ${D.cfg.max} 分钟内批，加急 3 分钟，特急 1 分钟；等不及可以「催办」。</div></details>
        <div class="oa-h">全部（${L.length}）· 通过 ${L.filter(x => x.res && x.res !== '驳回').length} · 驳回 ${L.filter(x => x.res === '驳回').length}</div>${L.filter(x => !(x.by === 'ta' && !x.res)).slice(0, 40).map(row).join('') || '<div class="gyx-tip">还没有报告</div>'}`);
};
X.ctx(id => { const L = D.list.filter(x => x.cid === String(id)); if (!L.length) return ''; const wait = L.filter(x => x.by === 'ta' && !x.res), mine = L.filter(x => x.by === 'me' && !x.res), last = L.find(x => x.res && Date.now() - x.rat < 864e5); return `【恋爱审批】${mine.length ? '她提交给你、你还没批的：' + mine.map(x => x.type + '（' + x.why.slice(0, 20) + '）').join('；') + '。' : ''}${wait.length ? '你提交给她、她还没批的：' + wait.map(x => x.type).join('、') + '。' : ''}${last ? `最近一单：${last.by === 'me' ? '她的' : '你的'}「${last.type}」被${last.res}${last.cond ? '（条件：' + last.cond + '）' : ''}。` : ''}`; }, 'gyxOA');
X.action({ key: 'gyx_oa', label: '给她打一份恋爱报告申请点什么', hint: '恋爱审批', need: c => !D.list.some(x => x.cid === String(c.id) && x.by === 'ta' && !x.res),
    run: async c => { const x = await taApply(c); X.notify(c, `🧾 ${X.esc(X.name(c))} ${X.v('给你提交了一份申请', '打了份报告等你批', '发起了一个审批流程')}：${X.esc(x.type)}`, x.why, () => window.gyxOAView(x.id)); X.say(c, `🧾 ${X.v('报告已提交，请领导审批。', '我交了一份申请，你快去批～', '流程发起了，等你盖章。')}（${x.type}）`); return '提交了' + x.type; } }, 'gyxOA');
X.today(() => { const rows = []; D.list.filter(x => x.by === 'ta' && !x.res).forEach(x => rows.push({ t: '待我批', x: icoOf(x.type) + ' ' + X.esc(x.type), go: `gyxOAView('${x.id}')` })); D.list.filter(x => x.res && X.day(new Date(x.rat)) === X.day()).slice(0, 4).forEach(x => rows.push({ t: x.res, x: X.esc(x.type), go: `gyxOAView('${x.id}')` })); return { title: '🧾 恋爱审批', rows }; }, 'gyxOA');
X.widget('gyxOAW', { n: '恋爱审批', sizes: ['s', 'm'], tap: () => window.gyxOAOpen(), r: w => { const todo = D.list.filter(x => x.by === 'ta' && !x.res), wait = D.list.filter(x => x.by === 'me' && !x.res); return X.gw(w, '🧾', '恋爱审批', [todo.length ? todo.length + ' 份待我批' : wait.length ? wait.length + ' 份审批中' : '打份报告？', D.list[0] ? X.esc(D.list[0].type) + (D.list[0].res ? ' · ' + D.list[0].res : '') : '']); } }, 'gyxOA');
X.memArr({ k: 'gyxOA', ico: '🧾', n: '恋爱审批', d: '打过的报告和批注', arr: () => D.list, text: x => x.type + '：' + x.why + (x.res ? '｜' + x.res + '：' + (x.note || '') : ''), edit: (x, v) => { const m = v.match(/^(.*?)：(.*?)(?:｜(.*?)：(.*))?$/); if (m) { x.why = m[2]; if (m[4] != null) x.note = m[4]; } }, meta: x => x.no + ' · ' + (x.by === 'me' ? '我提交' : 'TA 提交'), save: () => S.set('d', D) }, 'gyxOA');
X.css('gyxOACss', `.oa-form{border:1px solid #e3e6ea;border-radius:14px;padding:12px;background:#fbfcfd;font-size:13.5px}.oa-hd{display:flex;justify-content:space-between;align-items:baseline;border-bottom:2px solid #2f6fde;padding-bottom:6px;margin-bottom:8px}.oa-hd b{font-size:16px;color:#2f6fde}.oa-hd span{font-family:monospace;font-size:11.5px;color:#888}.oa-form table{width:100%;border-collapse:collapse}.oa-form th,.oa-form td{border:1px solid #e3e6ea;padding:6px 8px;text-align:left;vertical-align:top}.oa-form th{background:#f2f5f9;color:#666;font-weight:500;width:84px;white-space:nowrap}.oa-urg{padding:1px 8px;border-radius:8px;font-size:12px}.oa-urg.u0{background:#eef2f7}.oa-urg.u1{background:#fff1d6;color:#b26b00}.oa-urg.u2{background:#ffe0e0;color:#c62828}.oa-flow{display:flex;align-items:center;gap:6px;margin:12px 0;font-size:12px}.oa-flow span{padding:3px 10px;border-radius:10px;background:#eee;color:#999}.oa-flow span.on{background:#2f6fde;color:#fff}.oa-flow span.cur{background:#fff1d6;color:#b26b00}.oa-flow i{flex:1;height:2px;background:#ddd}.oa-res{display:flex;gap:12px;align-items:center}.oa-res b{font-size:16px}.oa-note{font-size:17px;margin:4px 0;color:#c0392b}.oa-res em{font-style:normal;font-size:11px;color:#aaa}.oa-stamp{transform:rotate(-14deg);flex:none}.oa-h{font-weight:700;margin:12px 0 4px}.oa-it{display:flex;gap:10px;align-items:center;padding:9px 4px;border-bottom:1px solid #f2f2f4;cursor:pointer}.oa-it>span{font-size:22px}.oa-it>div{flex:1}.oa-it em{display:block;font-style:normal;font-size:11px;color:#999;font-family:monospace}.oa-it>i{font-style:normal;font-size:12px;padding:2px 8px;border-radius:8px}.oa-it>i.ok{background:#e6f7ec;color:#1e8e3e}.oa-it>i.no{background:#f2f2f2;color:#888}.oa-it>i.wait{background:#fff1d6;color:#b26b00}`);
X.mini({ id: 'gyxOA', icon: '🧾', title: '恋爱审批', desc: 'OA 式打报告，互相审批盖章', cat: '一起做', onOpen: () => window.gyxOAOpen() });
(async () => { D = Object.assign(D, await S.get('d', {})); D.list = D.list || []; D.cfg = Object.assign({ max: 10 }, D.cfg || {}); setTimeout(tick, 15000); setInterval(tick, 30000); })();
