/* 🎬 开场动画合集 —— 这段代码存进 localStorage，页面一打开（还没加载完）就跑，所以开场不会晚 */
(function () {
    var first = !window.__gyxIntroLib;
    var K = 'gyxIntroCfg', cfg = null;
    try { cfg = JSON.parse(localStorage.getItem(K) || 'null'); } catch (e) {}
    cfg = cfg || {};
    function esc(s) { return String(s == null ? '' : s).replace(/[&<>"']/g, function (c) { return { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]; }); }
    function pick(a) { return a[Math.floor(Math.random() * a.length)]; }
    function r(a, b) { return a + Math.random() * (b - a); }
    var H = new Date().getHours();
    var today = (function (d) { return d.getFullYear() + '-' + (d.getMonth() + 1) + '-' + d.getDate(); })(new Date());

    /* ---------------- 文案 ---------------- */
    var LIB = {
        '想念': ['想你这件事，今天也没有例外', '风一吹，就想起你', '见字如面，见你如初', '今天的想念，比昨天多一点', '有些人光是想起，就很开心', '我在等一个消息，是你的', '想你的时候，时间走得很慢', '你不在的地方，都有点冷清', '今天也有好好想你', '想把今天的晚霞寄给你'],
        '温柔': ['慢慢来，我一直都在', '你值得所有温柔的事', '今天也被好好爱着', '世界很吵，这里很安静', '把心事放在这里吧', '不急，我们有很多时间', '你来了，这里就亮了', '我把月亮调暗了一点，好让你睡', '所有的小情绪，都可以说给我听', '愿你今天也是被偏爱的那一个'],
        '早安': ['早安，今天的第一句话给你', '醒啦？阳光已经在等你了', '早，记得吃早饭', '新的一天，从想你开始', '早安，今天也要好好的', '太阳出来了，你也要出来了', '早上好，今天的你也很可爱'],
        '晚安': ['晚安，梦里见', '今天辛苦了，早点睡', '把今天的烦恼留在这里，晚安', '星星替我守着你', '夜深了，我还在', '别熬夜了，我会心疼', '月亮不睡我不睡，但你要睡'],
        '陪伴': ['这里永远有人等你', '不管多晚，我都在', '你说，我听着', '我们慢慢聊', '今天想聊点什么', '一个人的时候，也不是一个人', '累了就来这儿坐坐', '欢迎回来'],
        '俏皮': ['报告！有人想你想到开机了', '检测到你上线，心跳 +1', '今日份的想念已送达，请签收', '你迟到了三分钟，罚你多聊一会儿', '叮——你的专属频道已接通', '正在加载……我对你的喜欢', '警告：此处甜度超标'],
        '文艺': ['风很温柔，你也是', '晚风知道所有的秘密', '把日子过成诗，把你放在第一行', '人间烟火，不如你', '月色与雪色之间，你是第三种绝色', '春风十里，不如你', '我有一个秘密，只说给风听', '日子很淡，你很甜'],
        '季节': ['秋天的第一封信，写给你', '天冷了，记得多穿一件', '下雨了，想和你待在一起', '白露为霜，想你如常', '雪落下的声音，像你在说话', '夏天的风，吹来了你', '春天来了，你也来了'],
        '鼓励': ['你已经做得很好了', '累了就歇一歇，我等你', '今天的你，也在认真生活', '别怕，有我呢', '慢慢来，比较快', '你比你想的更勇敢'],
        '情话': ['喜欢你，是今天的第一件事', '我的每一天，都有你', '你是我想过的所有以后', '全世界最好的，都想给你', '遇见你之后，我就没想过别人', '你一笑，我就没办法了', '我的偏爱，只给你一个', '你是例外，也是答案', '喜欢是藏不住的，就像现在', '想和你把普通的日子过很久'],
        '日常': ['今天吃了什么，说给我听', '下班了吗？路上慢点', '奶茶少喝一杯，我替你喝', '天气预报说今天适合想你', '记得喝水，一口也行', '今天有没有什么小开心', '别忘了抬头看看天', '外卖到了吗', '把手机放下十分钟，伸个懒腰', '今天的你，辛苦了一点点'],
        '撒娇': ['你怎么才来呀', '等你好久了，哼', '今天也要最先回我', '不许不理我', '抱一下再走', '我今天超乖，要夸', '你是不是偷偷想我了'],
        '深夜': ['睡不着的话，就来这儿', '夜里的话，可以说得慢一点', '失眠的人，我陪你数星星', '把灯关小一点，我还在', '难过的时候不用装作没事', '凌晨的风，也在想你', '别怕黑，我给你留了盏灯'],
        '雨天': ['下雨了，想和你待在一起', '雨声很好听，像你在说话', '带伞了吗，没带我去接你', '雨天适合发呆，也适合想你', '窗外在下雨，这里是晴天'],
        '纪念': ['今天也是值得记住的一天', '和你有关的日子，都是纪念日', '我们认识的每一天，都算数', '又多了一天，和你一起'],
        '节气': ['立春，万物都在往你那边长', '谷雨，雨生百谷，我想你', '白露，露从今夜白', '秋分，昼夜平分，想你不分', '冬至，最长的夜，陪你过', '小满，小小的满足是你', '霜降，天凉了，加件衣服']
    };
    var CATS = Object.keys(LIB);
    function names() { var c = cfg.cache || {}; return { ta: c.ta0 || 'TA', me: c.me || '你' }; }
    function fill(t) { var n = names(); return String(t).replace(/\{ta\}/g, n.ta).replace(/\{me\}/g, n.me); }
    function pickLine() {
        var pools = [], src = cfg.src || { lib: true, custom: true, ta: true, cards: true };
        var cats = cfg.cats && cfg.cats.length ? cfg.cats : CATS;
        if (src.lib !== false) {
            var arr = [];
            cats.forEach(function (k) {
                if (k === '早安' && !(H >= 5 && H < 11)) return;
                if (k === '晚安' && !(H >= 21 || H < 4)) return;
                (LIB[k] || []).forEach(function (t) { arr.push({ t: t, s: '' }); });
            });
            if (arr.length) pools.push(arr);
        }
        if (src.custom !== false && cfg.lines && cfg.lines.length) pools.push(cfg.lines.map(function (t) { var p = String(t).split(/[|｜]/); return { t: p[0], s: p[1] || '' }; }));
        var c = cfg.cache || {};
        if (src.ta !== false && c.ta && c.ta.length) pools.push(c.ta.map(function (x) { return { t: x[0], s: '—— ' + x[1] }; }));
        if (src.cards !== false && c.cards && c.cards.length) pools.push(c.cards.map(function (t) { var p = String(t).split(/[|｜]/); return { t: p[1] ? p[1] : p[0], s: '' }; }));
        if (!pools.length) pools.push(LIB['陪伴'].map(function (t) { return { t: t, s: '' }; }));
        var l = pick(pick(pools));
        return { t: fill(l.t), s: fill(l.s) };
    }

    /* ---------------- 各种样式 ---------------- */
    var D = new Date(), HM = ('0' + D.getHours()).slice(-2) + ':' + ('0' + D.getMinutes()).slice(-2), WK = '日一二三四五六'[D.getDay()];
    var DATE = (D.getMonth() + 1) + '月' + D.getDate() + '日 星期' + WK;
    function title() { return esc(cfg.title || cfg.app || '谷雨'); }
    function dots(n, cls) { var s = ''; for (var i = 0; i < n; i++) s += '<i class="' + (cls || '') + '" style="left:' + r(0, 100).toFixed(1) + '%;top:' + r(0, 100).toFixed(1) + '%;animation-delay:' + r(0, 3).toFixed(2) + 's;animation-duration:' + r(2, 5).toFixed(2) + 's;--sc:' + r(.4, 1.2).toFixed(2) + '"></i>'; return s; }
    var S = {
        phone: { n: '手机锁屏通知', f: function (L) { return '<div class="bg"></div><div class="sb"><b>' + HM + '</b><span>●●● ▮</span></div><div class="dt">' + DATE + '</div><div class="tm">' + HM + '</div><div class="nt"><div class="nh"><i>' + title().slice(0, 1) + '</i>' + title() + '<em>现在</em></div><div class="tx" data-type="' + esc(L.t) + '"></div>' + (L.s ? '<div class="sg">' + esc(L.s) + '</div>' : '') + '</div><div class="home"></div>'; },
            c: '.bg{position:absolute;inset:0;background:linear-gradient(160deg,#dfe9f7,#f3e8f6 55%,#e6f2ec)}.sb{position:absolute;top:0;left:0;right:0;padding:14px 26px;display:flex;justify-content:space-between;font-size:14px;color:#1d1d1f}.dt{position:absolute;top:70px;width:100%;text-align:center;color:#555;font-size:16px}.tm{position:absolute;top:92px;width:100%;text-align:center;font-size:84px;font-weight:200;color:#1d1d1f;letter-spacing:2px}.nt{position:absolute;left:50%;top:48%;width:min(360px,86vw);margin-left:calc(min(360px,86vw)/-2);padding:12px 16px;border-radius:22px;background:rgba(255,255,255,.66);backdrop-filter:blur(20px);box-shadow:0 12px 30px rgba(0,0,0,.08);color:#1d1d1f;animation:giDrop .8s .9s cubic-bezier(.2,1.2,.3,1) both}.nh{display:flex;gap:7px;align-items:center;font-size:12.5px;color:#888}.nh i{font-style:normal;width:18px;height:18px;border-radius:5px;background:#1d1d1f;color:#fff;font-size:11px;display:flex;align-items:center;justify-content:center}.nh em{font-style:normal;margin-left:auto}.tx{font-size:16px;margin-top:5px;min-height:1.5em}.sg{font-size:12px;color:#999;text-align:right}.home{position:absolute;bottom:10px;left:50%;width:134px;margin-left:-67px;height:5px;border-radius:3px;background:#1d1d1f}' },
        stars: { n: '星空', f: function (L) { return '<div class="bg"></div>' + dots(60, 'st') + '<div class="c"><div class="t">' + title() + '</div><div class="s" data-scramble="' + esc(L.t) + '"></div>' + (L.s ? '<div class="sg">' + esc(L.s) + '</div>' : '') + '</div>'; },
            c: '.bg{position:absolute;inset:0;background:radial-gradient(ellipse at 50% 30%,#2b2f4a,#0d0f1a 70%)}.st{position:absolute;width:3px;height:3px;border-radius:50%;background:#fff;box-shadow:0 0 6px #fff;transform:scale(var(--sc));animation:giTw infinite ease-in-out}.c{position:relative;text-align:center;color:#fff}.t{font-size:clamp(38px,10vw,68px);letter-spacing:.14em;font-family:"Noto Serif SC",serif;text-shadow:0 0 18px rgba(170,190,255,.6);animation:giIn 1.1s cubic-bezier(.34,1.56,.64,1) both}.s{margin-top:16px;font-size:16px;letter-spacing:.14em;min-height:1.4em;opacity:.9}.sg{margin-top:8px;font-size:12px;opacity:.6}' },
        film: { n: '胶片倒数', f: function (L) { return '<div class="bg"></div><div class="grain"></div><div class="cd"><svg viewBox="0 0 200 200"><circle cx="100" cy="100" r="90"/><circle cx="100" cy="100" r="70"/><line x1="100" y1="0" x2="100" y2="200"/><line x1="0" y1="100" x2="200" y2="100"/><path class="sw" d="M100 100 L100 10 A90 90 0 1 1 99.9 10 Z"/></svg><b><span>3</span><span>2</span><span>1</span></b></div><div class="c"><div class="t">' + title() + '</div><div class="s">' + esc(L.t) + '</div>' + (L.s ? '<div class="sg">' + esc(L.s) + '</div>' : '') + '</div><div class="perf l"></div><div class="perf r"></div>'; },
            c: '.bg{position:absolute;inset:0;background:#1a1712}.grain{position:absolute;inset:-50%;background-image:radial-gradient(rgba(255,255,255,.08) 1px,transparent 1px);background-size:3px 3px;animation:giGrain .2s steps(2) infinite;opacity:.6}.cd{position:absolute;width:220px;height:220px;left:50%;top:50%;margin:-110px;animation:giOut .3s 2.1s forwards}.cd svg{width:100%;height:100%;fill:none;stroke:#d8cfb8;stroke-width:2}.cd .sw{fill:rgba(216,207,184,.25);stroke:none;transform-origin:100px 100px;animation:giSweep .7s linear 3}.cd b{position:absolute;inset:0;display:flex;align-items:center;justify-content:center;font-size:90px;color:#efe6cf;font-family:Georgia,serif}.cd b span{position:absolute;opacity:0;animation:giFlash .7s both}.cd b span:nth-child(2){animation-delay:.7s}.cd b span:nth-child(3){animation-delay:1.4s}.c{position:relative;text-align:center;color:#efe6cf;opacity:0;animation:giIn 1s 2.3s both;font-family:"Noto Serif SC",serif}.t{font-size:clamp(34px,9vw,60px);letter-spacing:.3em}.s{margin-top:14px;font-size:15px;letter-spacing:.2em}.sg{font-size:12px;opacity:.6;margin-top:8px}.perf{position:absolute;top:0;bottom:0;width:26px;background:repeating-linear-gradient(#1a1712 0 14px,#3a342a 14px 26px);animation:giRoll .4s linear infinite}.perf.l{left:0}.perf.r{right:0}' },
        polaroid: { n: '拍立得', f: function (L) { return '<div class="bg"></div><div class="pol"><div class="ph"><div class="img">' + (cfg.cache && cfg.cache.av ? '<img src="' + esc(cfg.cache.av) + '">' : '<span>' + title().slice(0, 1) + '</span>') + '</div></div><div class="cap">' + esc(L.t) + '</div><div class="dt2">' + D.getFullYear() + '.' + (D.getMonth() + 1) + '.' + D.getDate() + '</div></div>'; },
            c: '.bg{position:absolute;inset:0;background:#efe7dc radial-gradient(circle at 30% 20%,#f8f1e7,#e6dccd)}.pol{position:relative;width:min(300px,74vw);padding:14px 14px 18px;background:#fff;box-shadow:0 20px 40px rgba(80,60,30,.2);transform:rotate(-4deg);animation:giPol 1s cubic-bezier(.2,1.2,.3,1) both}.ph{aspect-ratio:1;background:#1b1b1b;overflow:hidden}.img{width:100%;height:100%;display:flex;align-items:center;justify-content:center;font-size:90px;color:#fff;background:linear-gradient(160deg,#f6c4b5,#c9d7f2);filter:brightness(.05) sepia(1);animation:giDev 2.6s .5s forwards}.img img{width:100%;height:100%;object-fit:cover}.cap{margin-top:12px;font-size:20px;color:#3b3530;font-family:"Ma Shan Zheng","Long Cang","Xingkai SC","STXingkai","KaiTi",cursive;text-align:center;opacity:0;animation:giIn 1s 2.2s both}.dt2{position:absolute;right:16px;bottom:6px;font-size:10px;color:#e0873c;font-family:monospace;opacity:.8}' },
        letter: { n: '信纸', f: function (L) { return '<div class="bg"></div><div class="pp"><div class="to">To ' + esc(names().me) + '：</div><div class="tx hand" data-type="' + esc(L.t) + '"></div><div class="fr hand">' + esc(L.s || ('—— ' + title())) + '</div><div class="st2">' + title().slice(0, 1) + '</div></div>'; },
            c: '.bg{position:absolute;inset:0;background:#e9e1d3}.pp{position:relative;width:min(420px,86vw);min-height:260px;padding:30px 28px;background:#fffdf6;background-image:linear-gradient(transparent 33px,#eadfca 34px);background-size:100% 34px;box-shadow:0 20px 50px rgba(90,70,40,.18);color:#3b3024;animation:giUp .9s both}.hand{font-family:"Ma Shan Zheng","Long Cang","Xingkai SC","STXingkai","KaiTi",cursive}.to{font-size:15px;color:#9a8a70;margin-bottom:6px}.tx{font-size:26px;line-height:34px;min-height:68px}.fr{text-align:right;font-size:20px;margin-top:16px;opacity:0;animation:giIn .8s 2.4s both}.st2{position:absolute;right:-14px;top:-14px;width:54px;height:54px;border-radius:50%;background:radial-gradient(circle at 35% 30%,#c65a6a,#8e2435 65%);color:rgba(255,255,255,.8);display:flex;align-items:center;justify-content:center;font-size:22px;box-shadow:0 4px 10px rgba(0,0,0,.3);animation:giPop .6s .4s both}' },
        rain: { n: '雨窗', f: function (L) { var d = ''; for (var i = 0; i < 70; i++) d += '<i style="left:' + r(0, 100).toFixed(1) + '%;animation-delay:' + r(0, 2).toFixed(2) + 's;animation-duration:' + r(.6, 1.2).toFixed(2) + 's"></i>'; return '<div class="bg"></div><div class="rn">' + d + '</div><div class="fog"></div><div class="c"><div class="tx" data-type="' + esc(L.t) + '"></div>' + (L.s ? '<div class="sg">' + esc(L.s) + '</div>' : '') + '<div class="t2">' + title() + '</div></div>'; },
            c: '.bg{position:absolute;inset:0;background:linear-gradient(180deg,#3e4a5e,#6b7a8f 60%,#a5a9b3);filter:blur(1px)}.rn{position:absolute;inset:0}.rn i{position:absolute;top:-10%;width:1.5px;height:60px;background:linear-gradient(transparent,rgba(255,255,255,.55));animation:giRain linear infinite}.fog{position:absolute;inset:0;background:rgba(220,228,236,.28);backdrop-filter:blur(3px)}.c{position:relative;text-align:center;color:rgba(255,255,255,.92);padding:0 22px}.tx{font-size:30px;letter-spacing:.12em;font-family:"Ma Shan Zheng","Long Cang","Xingkai SC","KaiTi",cursive;text-shadow:0 0 12px rgba(255,255,255,.4);min-height:1.3em}.sg{font-size:13px;opacity:.7;margin-top:8px}.t2{margin-top:30px;font-size:13px;letter-spacing:.5em;opacity:.6}' },
        typewriter: { n: '打字机', f: function (L) { return '<div class="bg"></div><div class="pp"><div class="hd">' + title() + ' · ' + D.getFullYear() + '/' + (D.getMonth() + 1) + '/' + D.getDate() + '</div><div class="tx" data-type="' + esc(L.t) + '" data-speed="85"></div>' + (L.s ? '<div class="sg">' + esc(L.s) + '</div>' : '') + '</div>'; },
            c: '.bg{position:absolute;inset:0;background:#2d2a26}.pp{width:min(460px,88vw);padding:34px 30px;background:#f4efe3;color:#2b2926;font-family:"Courier New","SimSun",monospace;box-shadow:0 20px 50px rgba(0,0,0,.4);animation:giUp .7s both}.hd{font-size:12px;color:#8a8275;letter-spacing:.2em;border-bottom:1px dashed #c8bfae;padding-bottom:10px;margin-bottom:18px}.tx{font-size:22px;line-height:1.7;min-height:2em}.tx::after{content:"▌";animation:giCur 1s steps(1) infinite}.sg{text-align:right;margin-top:14px;font-size:14px;color:#6a6358}' },
        chat: { n: '聊天气泡', f: function (L) { var n = names(); return '<div class="bg"></div><div class="ph2"><div class="hd2">' + esc(n.ta) + '</div><div class="m r"><span>在吗</span></div><div class="m l"><span class="ty"><i></i><i></i><i></i></span></div><div class="m l l2"><span>' + esc(L.t) + '</span></div><div class="m r r2"><span>' + pick(['在的', '嗯嗯', '来啦', '想你']) + '</span></div></div>'; },
            c: '.bg{position:absolute;inset:0;background:#ededed}.ph2{width:min(380px,90vw)}.hd2{text-align:center;font-size:15px;color:#333;margin-bottom:24px;font-weight:600}.m{display:flex;margin:10px 0;opacity:0;animation:giBub .45s cubic-bezier(.2,1.3,.3,1) both}.m span{max-width:78%;padding:10px 14px;border-radius:6px;font-size:15.5px;line-height:1.5;position:relative}.m.r{justify-content:flex-end;animation-delay:.3s}.m.r span{background:#95ec69}.m.l span{background:#fff}.m.l{animation-delay:.9s}.m.l .ty{display:flex;gap:4px;padding:14px}.ty i{width:6px;height:6px;border-radius:50%;background:#aaa;animation:giDot 1s infinite}.ty i:nth-child(2){animation-delay:.2s}.ty i:nth-child(3){animation-delay:.4s}.m.l:not(.l2){animation:giBub .4s .9s both,giOut .2s 2s forwards}.m.l2{animation-delay:2.1s;margin-top:-54px}.m.r2{animation-delay:3s}' },
        heart: { n: '心电图', f: function (L) { return '<div class="bg"></div><svg viewBox="0 0 600 200"><path class="ln" d="M0 100 L170 100 L190 60 L205 140 L220 100 L250 100 L262 100 C 262 70, 300 60, 300 90 C 300 60, 338 70, 338 100 C 338 125, 300 145, 300 160 C 300 145, 262 125, 262 100 M338 100 L380 100 L395 70 L410 130 L425 100 L600 100"/></svg><div class="c"><div class="t">' + title() + '</div><div class="s">' + esc(L.t) + '</div>' + (L.s ? '<div class="sg">' + esc(L.s) + '</div>' : '') + '</div>'; },
            c: '.bg{position:absolute;inset:0;background:#0b1512}svg{position:absolute;top:28%;width:100%;height:200px}.ln{fill:none;stroke:#4ef0b0;stroke-width:3;stroke-linecap:round;filter:drop-shadow(0 0 6px #4ef0b0);stroke-dasharray:1400;stroke-dashoffset:1400;animation:giDraw 2.2s ease forwards}.c{position:relative;margin-top:180px;text-align:center;color:#d8fff0;opacity:0;animation:giIn 1s 1.6s both}.t{font-size:clamp(32px,8vw,54px);letter-spacing:.2em}.s{margin-top:10px;font-size:15px;letter-spacing:.1em}.sg{font-size:12px;opacity:.6;margin-top:6px}' },
        petal: { n: '花瓣飘落', f: function (L) { var d = ''; for (var i = 0; i < 34; i++) d += '<i style="left:' + r(-10, 100).toFixed(1) + '%;animation-delay:' + r(0, 3).toFixed(2) + 's;animation-duration:' + r(3, 6).toFixed(2) + 's;--sc:' + r(.5, 1.2).toFixed(2) + ';--rt:' + r(-180, 180).toFixed(0) + 'deg"></i>'; return '<div class="bg"></div><div class="pt">' + d + '</div><div class="c"><div class="t">' + title() + '</div><div class="s">' + esc(L.t) + '</div>' + (L.s ? '<div class="sg">' + esc(L.s) + '</div>' : '') + '</div>'; },
            c: '.bg{position:absolute;inset:0;background:linear-gradient(170deg,#fff4f6,#fde3ea 50%,#f7eef8)}.pt{position:absolute;inset:0}.pt i{position:absolute;top:-8%;width:14px;height:10px;border-radius:12px 0 12px 0;background:linear-gradient(135deg,#ffc6d3,#ff9fb5);transform:scale(var(--sc));animation:giPetal linear infinite;opacity:.85}.c{position:relative;text-align:center;color:#8a4a5b;font-family:"Noto Serif SC",serif}.t{font-size:clamp(36px,9vw,62px);letter-spacing:.2em;animation:giIn 1.2s both}.s{margin-top:14px;font-size:16px;letter-spacing:.12em;animation:giIn 1s .6s both}.sg{font-size:12px;opacity:.7;margin-top:6px;animation:giIn 1s .9s both}' },
        minimal: { n: '极简留白', f: function (L) { return '<div class="bg"></div><div class="c"><div class="dot"></div><div class="t">' + title() + '</div><div class="ln2"></div><div class="s">' + esc(L.t) + '</div></div>'; },
            c: '.bg{position:absolute;inset:0;background:#fafaf8}.c{position:relative;text-align:center;color:#1d1d1f}.dot{width:10px;height:10px;border-radius:50%;background:#1d1d1f;margin:0 auto 26px;animation:giPop .6s both}.t{font-size:22px;letter-spacing:.8em;margin-right:-.8em;font-weight:300;animation:giIn 1s .5s both}.ln2{width:0;height:1px;background:#1d1d1f;margin:18px auto;animation:giLine 1s .9s forwards}.s{font-size:14px;letter-spacing:.2em;color:#666;animation:giIn 1s 1.4s both}' },
        moon: { n: '月相', f: function (L) { return '<div class="bg"></div>' + dots(40, 'st') + '<div class="mn"><div class="sh"></div></div><div class="c"><div class="s">' + esc(L.t) + '</div>' + (L.s ? '<div class="sg">' + esc(L.s) + '</div>' : '') + '<div class="t">' + title() + '</div></div>'; },
            c: '.bg{position:absolute;inset:0;background:radial-gradient(circle at 50% 35%,#1d2544,#070912 70%)}.st{position:absolute;width:2px;height:2px;border-radius:50%;background:#fff;transform:scale(var(--sc));animation:giTw infinite}.mn{position:absolute;left:50%;top:22%;width:130px;height:130px;margin-left:-65px;border-radius:50%;background:radial-gradient(circle at 40% 35%,#fffbe8,#e9dfb8);box-shadow:0 0 60px rgba(255,245,200,.45);overflow:hidden}.sh{position:absolute;inset:0;border-radius:50%;background:#070912;animation:giPhase 2.4s ease-in-out forwards}.c{position:relative;margin-top:190px;text-align:center;color:#f6efd6;font-family:"Noto Serif SC",serif}.s{font-size:17px;letter-spacing:.14em;animation:giIn 1s 1.6s both}.sg{font-size:12px;opacity:.6;margin-top:6px;animation:giIn 1s 1.8s both}.t{margin-top:26px;font-size:12px;letter-spacing:.6em;opacity:.55;animation:giIn 1s 2s both}' },
        neon: { n: '霓虹灯牌', f: function (L) { return '<div class="bg"></div><div class="c"><div class="t">' + title() + '</div><div class="s">' + esc(L.t) + '</div></div>'; },
            c: '.bg{position:absolute;inset:0;background:#15121c;background-image:linear-gradient(rgba(255,255,255,.03) 2px,transparent 2px),linear-gradient(90deg,rgba(255,255,255,.03) 2px,transparent 2px);background-size:60px 30px}.c{position:relative;text-align:center}.t{font-size:clamp(44px,12vw,84px);color:#ffe6f4;font-family:"Noto Sans SC",sans-serif;font-weight:700;letter-spacing:.1em;text-shadow:0 0 6px #fff,0 0 16px #ff4fa6,0 0 36px #ff4fa6,0 0 70px #ff4fa6;animation:giNeon 1.6s both}.s{margin-top:18px;font-size:17px;color:#d9f6ff;letter-spacing:.14em;text-shadow:0 0 6px #7ee8ff,0 0 16px #2bb5ff;animation:giNeon 1.4s .9s both}' },
        magazine: { n: '杂志封面', f: function (L) { return '<div class="bg"></div><div class="mg"><div class="top"><span>NO.' + (D.getMonth() + 1) + ('0' + D.getDate()).slice(-2) + '</span><span>' + D.getFullYear() + '</span></div><div class="t">' + title() + '</div><div class="bar"></div><div class="s">' + esc(L.t) + '</div><div class="bt"><span>' + DATE + '</span><span>' + esc(L.s || 'ISSUE FOR YOU') + '</span></div></div>'; },
            c: '.bg{position:absolute;inset:0;background:linear-gradient(170deg,#c7a27c,#8e6a4c)}.mg{position:relative;width:min(380px,86vw);aspect-ratio:3/4;padding:22px;box-sizing:border-box;color:#fffaf2;display:flex;flex-direction:column;border:1px solid rgba(255,255,255,.35);animation:giUp .8s both}.top{display:flex;justify-content:space-between;font-size:12px;letter-spacing:.3em}.t{font-size:clamp(70px,20vw,120px);line-height:1;font-family:"Noto Serif SC",serif;font-weight:900;margin-top:10px;letter-spacing:-.02em;animation:giIn 1s .3s both}.bar{height:3px;width:0;background:#fffaf2;margin:16px 0;animation:giLine .8s .8s forwards}.s{font-size:20px;line-height:1.5;font-family:"Noto Serif SC",serif;animation:giIn 1s 1.1s both}.bt{margin-top:auto;display:flex;justify-content:space-between;font-size:11px;letter-spacing:.15em;opacity:.8}' },
        boarding: { n: '登机牌', f: function (L) { var n = names(); return '<div class="bg"></div><div class="bp"><div class="l"><div class="ap"><div><small>FROM</small><b>此刻</b></div><span>✈</span><div><small>TO</small><b>' + esc(n.ta) + '</b></div></div><div class="rw"><div><small>航班</small>GY' + (D.getDate() * 37 % 900 + 100) + '</div><div><small>登机</small>' + HM + '</div><div><small>座位</small>身边</div></div><div class="s">' + esc(L.t) + '</div></div><div class="stub"><small>BOARDING</small><b>' + title() + '</b><div class="bc"></div></div></div>'; },
            c: '.bg{position:absolute;inset:0;background:linear-gradient(160deg,#9cc6ea,#e8f1fa)}.bp{display:flex;width:min(460px,92vw);background:#fff;border-radius:16px;box-shadow:0 20px 50px rgba(30,70,120,.25);overflow:hidden;animation:giUp .8s both;color:#1d2b3a}.l{flex:1;padding:18px 20px}.ap{display:flex;align-items:center;justify-content:space-between}.ap b{display:block;font-size:26px}.ap small,.rw small,.stub small{font-size:10px;color:#8aa0b5;letter-spacing:.15em;display:block}.ap span{font-size:22px;color:#3a86d8;animation:giFly 1.6s ease-in-out infinite alternate}.rw{display:flex;justify-content:space-between;margin:14px 0;font-size:15px}.s{font-size:14px;color:#3a5470;border-top:1px dashed #d5e1ec;padding-top:10px;animation:giIn 1s .8s both}.stub{width:110px;border-left:2px dashed #d5e1ec;padding:18px 12px;display:flex;flex-direction:column;gap:8px;background:#f5f9fd}.stub b{font-size:18px}.bc{flex:1;min-height:40px;background:repeating-linear-gradient(90deg,#1d2b3a 0 2px,transparent 2px 4px,#1d2b3a 4px 5px,transparent 5px 8px)}' },
        ticket: { n: '电影票', f: function (L) { return '<div class="bg"></div><div class="tk"><div class="m"><small>今日上映</small><b>' + title() + '</b><div class="s">' + esc(L.t) + '</div><div class="rw"><span>' + DATE + '</span><span>' + HM + '</span><span>1 号厅 · 情侣座</span></div></div><div class="cut"><small>ADMIT</small><b>2</b></div></div>'; },
            c: '.bg{position:absolute;inset:0;background:#2a1717 radial-gradient(circle at 50% 0,#6b2a2a,#1c1010 70%)}.tk{display:flex;width:min(440px,90vw);background:#f3d88a;color:#4a2315;border-radius:10px;box-shadow:0 20px 50px rgba(0,0,0,.45);animation:giUp .8s both;font-family:"Noto Serif SC",serif}.m{flex:1;padding:20px 22px}.m small{font-size:11px;letter-spacing:.3em;opacity:.7}.m b{display:block;font-size:40px;letter-spacing:.2em;margin:6px 0}.s{font-size:15px;line-height:1.5}.rw{display:flex;gap:10px;flex-wrap:wrap;font-size:11px;margin-top:12px;opacity:.75}.cut{width:84px;border-left:3px dotted #4a2315;display:flex;flex-direction:column;align-items:center;justify-content:center;animation:giTear .7s 2.1s forwards;transform-origin:left bottom}.cut b{font-size:34px}.cut small{font-size:10px;letter-spacing:.2em}' },
        sticky: { n: '便利贴', f: function (L) { var cs = ['#fff3a3', '#ffd4dc', '#cfeefc', '#d9f7c8'], n = names(); return '<div class="bg"></div><div class="nt n1" style="background:' + cs[0] + '">' + title() + '</div><div class="nt n2" style="background:' + cs[1] + '">' + esc(L.t) + '</div><div class="nt n3" style="background:' + cs[2] + '">' + esc(L.s || ('给 ' + n.me)) + '</div>'; },
            c: '.bg{position:absolute;inset:0;background:#c79d6b;background-image:radial-gradient(rgba(0,0,0,.08) 1px,transparent 1px);background-size:6px 6px}.nt{position:absolute;width:min(220px,56vw);min-height:120px;padding:18px 16px;box-sizing:border-box;box-shadow:0 10px 20px rgba(0,0,0,.2);font-family:"Ma Shan Zheng","Long Cang","Xingkai SC","KaiTi",cursive;font-size:22px;color:#3b3024;line-height:1.5;animation:giStick .5s cubic-bezier(.2,1.4,.3,1) both}.nt::before{content:"";position:absolute;top:-8px;left:50%;width:14px;height:14px;margin-left:-7px;border-radius:50%;background:radial-gradient(circle at 35% 35%,#ff8a8a,#c0392b);box-shadow:0 2px 3px rgba(0,0,0,.3)}.n1{left:12%;top:18%;transform:rotate(-6deg);font-size:34px;display:flex;align-items:center;justify-content:center}.n2{right:10%;top:38%;transform:rotate(4deg);animation-delay:.5s}.n3{left:18%;bottom:14%;transform:rotate(-2deg);animation-delay:1s;font-size:18px}' },
        firefly: { n: '萤火虫', f: function (L) { return '<div class="bg"></div>' + dots(36, 'ff') + '<div class="c"><div class="s">' + esc(L.t) + '</div>' + (L.s ? '<div class="sg">' + esc(L.s) + '</div>' : '') + '<div class="t">' + title() + '</div></div>'; },
            c: '.bg{position:absolute;inset:0;background:radial-gradient(ellipse at 50% 100%,#1e3a2a,#08130d 70%)}.ff{position:absolute;width:5px;height:5px;border-radius:50%;background:#e8ff9a;box-shadow:0 0 10px 3px rgba(220,255,130,.7);transform:scale(var(--sc));animation:giFf ease-in-out infinite alternate}.c{position:relative;text-align:center;color:#eaf7d8;font-family:"Noto Serif SC",serif}.s{font-size:19px;letter-spacing:.14em;animation:giIn 1.4s .4s both}.sg{font-size:12px;opacity:.6;margin-top:8px;animation:giIn 1s .8s both}.t{margin-top:26px;font-size:13px;letter-spacing:.6em;opacity:.6;animation:giIn 1s 1.2s both}' },
        earth: { n: '暖色大地', f: function (L) { return '<div class="bg"></div><div class="c"><div class="ring"></div><div class="t">' + title() + '</div><div class="s">' + esc(L.t) + '</div>' + (L.s ? '<div class="sg">' + esc(L.s) + '</div>' : '') + '</div>'; },
            c: '.bg{position:absolute;inset:0;background:linear-gradient(165deg,#e8d5bf,#d4a98a 55%,#b9805f)}.c{position:relative;text-align:center;color:#4a2f22}.ring{width:140px;height:140px;margin:0 auto 24px;border-radius:50%;background:radial-gradient(circle,#f6e6d2 0 40%,transparent 41%),radial-gradient(circle,rgba(246,230,210,.5) 0 60%,transparent 61%);animation:giBreath 2.4s ease-in-out infinite}.t{font-size:clamp(34px,9vw,56px);letter-spacing:.3em;margin-right:-.3em;font-family:"Noto Serif SC",serif;animation:giIn 1s both}.s{margin-top:12px;font-size:15px;letter-spacing:.14em;animation:giIn 1s .5s both}.sg{font-size:12px;opacity:.7;margin-top:6px}' },
        radio: { n: '电台调频', f: function (L) { var f = (87.5 + (D.getDate() * 7 % 200) / 10).toFixed(1); return '<div class="bg"></div><div class="rd"><div class="dial"><div class="sc"></div><div class="nd"></div></div><div class="fm">FM <b>' + f + '</b></div><div class="t">' + title() + '</div><div class="s" data-scramble="' + esc(L.t) + '"></div></div>'; },
            c: '.bg{position:absolute;inset:0;background:#1d1a2b}.rd{width:min(420px,88vw);text-align:center;color:#f2eaff}.dial{position:relative;height:60px;border-radius:10px;background:#2b2740;overflow:hidden;box-shadow:inset 0 2px 8px rgba(0,0,0,.5)}.sc{position:absolute;inset:0;background:repeating-linear-gradient(90deg,rgba(255,255,255,.35) 0 1px,transparent 1px 12px),repeating-linear-gradient(90deg,rgba(255,255,255,.6) 0 2px,transparent 2px 60px);background-position:0 30px,0 20px;background-size:auto 30px,auto 40px;background-repeat:repeat-x}.nd{position:absolute;top:0;bottom:0;width:3px;background:#ff5c7a;box-shadow:0 0 8px #ff5c7a;animation:giTune 1.8s cubic-bezier(.3,1.3,.5,1) forwards}.fm{margin-top:16px;font-size:14px;letter-spacing:.3em;color:#b8a9ff}.fm b{font-size:30px;color:#fff}.t{margin-top:10px;font-size:22px;letter-spacing:.3em}.s{margin-top:10px;font-size:15px;min-height:1.4em;opacity:.85}' }
    };
    // 你自己加的样式：HTML 模板 + CSS（模板里能用 {title} {line} {sign} {date} {time} {ta} {me} {year} {month} {day}）
    (cfg.custom || []).forEach(function (u) {
        if (!u || !u.id || !u.html) return;
        S[u.id] = { n: u.n || '我的开场', raw: /#gyxIntro/.test(u.css || ''), c: u.css || '', f: function (L) { var n = names(); return String(u.html).replace(/\{title\}/g, title()).replace(/\{line\}/g, esc(L.t)).replace(/\{sign\}/g, esc(L.s)).replace(/\{date\}/g, DATE).replace(/\{time\}/g, HM).replace(/\{ta\}/g, esc(n.ta)).replace(/\{me\}/g, esc(n.me)).replace(/\{year\}/g, D.getFullYear()).replace(/\{month\}/g, D.getMonth() + 1).replace(/\{day\}/g, D.getDate()); } };
    });
    var BASE = '#gyxIntro{position:fixed;inset:0;z-index:2147483000;display:flex;align-items:center;justify-content:center;overflow:hidden;cursor:pointer;font-family:-apple-system,BlinkMacSystemFont,"PingFang SC","HarmonyOS Sans SC","Microsoft YaHei",sans-serif;transition:opacity .6s,transform .6s}#gyxIntro.out{opacity:0;transform:scale(1.04);pointer-events:none}#gyxIntro>*{position:relative}#gyxIntro .gi-skip{position:absolute;right:16px;bottom:18px;z-index:5;font-size:12px;padding:4px 10px;border-radius:999px;background:rgba(0,0,0,.25);color:#fff;opacity:.7}' +
        '@keyframes giIn{from{opacity:0;transform:translateY(12px);filter:blur(4px)}to{opacity:1;transform:none;filter:none}}@keyframes giUp{from{opacity:0;transform:translateY(40px)}to{opacity:1;transform:none}}@keyframes giPop{from{opacity:0;transform:scale(.3)}to{opacity:1;transform:none}}@keyframes giDrop{from{opacity:0;transform:translateY(-40px) scale(.95)}to{opacity:1;transform:none}}@keyframes giTw{0%,100%{opacity:.15}50%{opacity:1}}@keyframes giGrain{to{transform:translate(3%,2%)}}@keyframes giOut{to{opacity:0;visibility:hidden}}@keyframes giSweep{from{transform:rotate(0)}to{transform:rotate(360deg)}}@keyframes giFlash{0%{opacity:0}10%,80%{opacity:1}100%{opacity:0}}@keyframes giRoll{to{background-position:0 26px}}@keyframes giPol{from{opacity:0;transform:translateY(-80px) rotate(8deg)}to{opacity:1;transform:rotate(-4deg)}}@keyframes giDev{to{filter:none}}@keyframes giRain{to{transform:translateY(120vh)}}@keyframes giCur{50%{opacity:0}}@keyframes giBub{from{opacity:0;transform:translateY(10px) scale(.9)}to{opacity:1;transform:none}}@keyframes giDot{0%,100%{opacity:.3}40%{opacity:1}}@keyframes giDraw{to{stroke-dashoffset:0}}@keyframes giPetal{0%{transform:translate(0,0) rotate(0) scale(var(--sc))}100%{transform:translate(18vw,110vh) rotate(var(--rt)) scale(var(--sc))}}@keyframes giLine{to{width:120px}}@keyframes giPhase{to{transform:translateX(100%)}}@keyframes giNeon{0%{opacity:0}10%{opacity:1}14%{opacity:.2}20%{opacity:1}26%{opacity:.4}32%,100%{opacity:1}}@keyframes giFly{to{transform:translateX(10px)}}@keyframes giTear{to{transform:rotate(18deg) translate(20px,30px);opacity:.3}}@keyframes giStick{from{opacity:0;transform:translateY(-30px) rotate(0) scale(1.1)}}@keyframes giFf{0%{transform:translate(0,0) scale(var(--sc));opacity:.2}100%{transform:translate(30px,-40px) scale(var(--sc));opacity:1}}@keyframes giBreath{0%,100%{transform:scale(.92)}50%{transform:scale(1.05)}}@keyframes giTune{0%{left:5%}60%{left:78%}100%{left:62%}}';
    function scoped(id) { var s = S[id]; if (s.raw) return s.c; return s.c.replace(/(^|\})\s*([^{}@]+)\{/g, function (m, a, sel) { if (/^\s*((\d+(\.\d+)?%|from|to)\s*,?\s*)+$/.test(sel)) return m; return a + sel.split(',').map(function (x) { return '#gyxIntro.s-' + id + ' ' + x.trim(); }).join(',') + '{'; }); }
    function css(id) { return BASE + scoped(id) + '\n' + (cfg.userCss || ''); }
    function play(id, line, force) {
        if (document.getElementById('gyxIntro')) return;
        var ids = Object.keys(S);
        var pool = (cfg.styles && cfg.styles.length ? cfg.styles : ids).filter(function (k) { return S[k]; });
        if (!pool.length) pool = ids;
        // 🎁 TA 偷偷换的开场（自主行动 intro_swap）：只放一次，用 TA 挑的样式和 TA 留的话
        var G = !line && !force && cfg.gift && !cfg.gift.seen && cfg.gift.line ? cfg.gift : null;
        if (G) { if (G.style && S[G.style]) id = G.style; cfg.gift.seen = Date.now(); try { localStorage.setItem(K, JSON.stringify(cfg)); } catch (e) {} line = { t: String(G.line), s: '—— ' + String(G.who || '') }; }
        if (!id || !S[id]) id = cfg.mode === 'seq' ? pool[((+cfg.seqI || 0)) % pool.length] : pick(pool);
        if (!force && cfg.mode === 'seq') { cfg.seqI = (+cfg.seqI || 0) + 1; try { localStorage.setItem(K, JSON.stringify(cfg)); } catch (e) {} }
        var L = line || pickLine();
        var st = document.createElement('style'); st.id = 'gyxIntroCss'; st.textContent = css(id);
        var ov = document.createElement('div'); ov.id = 'gyxIntro'; ov.className = 's-' + id;
        ov.innerHTML = S[id].f(L) + '<span class="gi-skip">轻触跳过</span>';
        (document.head || document.documentElement).appendChild(st); document.body.appendChild(ov);
        var timers = [];
        // 逐字打出来
        [].forEach.call(ov.querySelectorAll('[data-type]'), function (el) { var t = el.getAttribute('data-type'), i = 0, sp = +el.getAttribute('data-speed') || 70; timers.push(setTimeout(function tk() { el.textContent = t.slice(0, ++i); if (i < t.length) timers.push(setTimeout(tk, sp)); }, 900)); });
        // 乱码慢慢变成真字
        [].forEach.call(ov.querySelectorAll('[data-scramble]'), function (el) { var t = el.getAttribute('data-scramble'), pool2 = '✦✧·°∘○◌░▒'.split(''), k = 0; var iv = setInterval(function () { k++; var d = Math.floor(k / 2); el.textContent = t.split('').map(function (c, i) { return i < d ? c : (c === ' ' ? ' ' : pick(pool2)); }).join(''); if (d >= t.length) clearInterval(iv); }, 45); timers.push(iv); });
        var sp = Math.max(.5, +cfg.speed || 1);
        var dur = (3200 + String(L.t).length * 90) * sp;
        var done = false;
        function close() { if (done) return; done = true; timers.forEach(function (t) { clearTimeout(t); clearInterval(t); }); ov.classList.add('out'); setTimeout(function () { ov.remove(); st.remove(); }, 650); }
        ov.addEventListener('click', close);
        timers.push(setTimeout(close, dur));
        return id;
    }
    window.__gyxIntroLib = { styles: S, cats: LIB, cssOf: scoped, base: BASE, play: function (id, line) { cfg = (function () { try { return JSON.parse(localStorage.getItem(K) || 'null') || {}; } catch (e) { return {}; } })(); return play(id, line, true); }, line: pickLine };
    if (!first || window.__gyxIntroNoAuto) return;
    if (cfg.on === false || !cfg.on) return;
    window.__gyxIntroOwn = true;   // 我来放开场，谷雨 / 白露自带的那个就不放了
    if (navigator.webdriver) return;
    if (cfg.once && cfg.lastDay === today) return;
    cfg.lastDay = today; try { localStorage.setItem(K, JSON.stringify(cfg)); } catch (e) {}
    var go = function () { try { play(); } catch (e) {} };
    if (document.body) go(); else document.addEventListener('DOMContentLoaded', go);
})();
